name: Scala CI

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - uses: dorny/paths-filter@v2.2.1
      id: filter
      with:
        filters: |
          noMessaging:
            - 'ecosim/**'
          compiler:
            - 'core/**'
          library:
            - 'library/**'
          example:
            - 'example/**'
          generatedExample:
            - 'generated/**'
    - name: noMessaging test
      if: ${{ steps.filter.outputs.noMessaging == 'true' }}
      run: sbt "project noMessaging; test"
  
    - name: compiler test
      if: ${{ steps.filter.outputs.compiler == 'true' }}
      run: sbt "project core; test; project genCore; test"
  
    - name: library test
      if: ${{ steps.filter.outputs.library == 'true' }}
      run: sbt "project library; test"
    
    - name: examples compile and run
      if: ${{ steps.filter.outputs.generatedExample == 'true' || steps.filter.outputs.example == 'true' || steps.filter.outputs.library == 'true' || steps.filter.outputs.compiler == 'true'}}
      run: sbt "project example; runAll; project genExample; testOnly generated.example.test.generatedExamples"
